### ISSUE TITLE
`AsRef<Path>` instead of `AsRef<Self>` in `Utf8Path::starts_with`?

### ISSUE THREAD

**Issue by smoelius** [camino-rs/camino#12]
Mostly because I am curious, what is the rationale for requiring `base` to implement `AsRef<Path>` instead of  `AsRef<Self>` in `Utf8Path::starts_with`?
https://github.com/camino-rs/camino/blob/8aa72052754a3b8d3b9ec1fe95391fb06365608c/src/lib.rs#L817

**Comment by sunshowers** [comment]
Hi @smoelius--great question, thanks for asking!

Consider what happens if you have a `Path` -- it is reasonable to ask if a `Utf8Path` starts with a `Path`, and camino can answer that for you.

The same applies to other third party types that implement `AsRef<Path>`. consider what happens if there's another third party type `MyPath` which is unaware of camino but implements `AsRef<Path>`.

So `impl AsRef<Path>` is more general than `AsRef<Self>`.

**Comment by smoelius** [comment]
Got it. Thank you for the explanation.
