### ISSUE TITLE
impl JsonSchema on Utf8Path[Buf]

### ISSUE THREAD

**Issue by aidanwolter3** [camino-rs/camino#91]
I would like to use the [`schemars`](https://github.com/GREsau/schemars) crate in a project that heavily uses `camino`, but am currently prevented from doing so because `Utf8Path[Buf]` does not implement `schemars::JsonSchema`.

This PR in `schemars` has not gone anywhere because the maintainer has not reviewed it.
https://github.com/GREsau/schemars/pull/214

Could we add these impls in `camino` instead?

**Comment by sunshowers** [comment]
Thanks for the question! Sadly no, that wouldn't be the right thing to do, because it would mean that none of the many crates that schemars depends on could depend on camino.

However you can do [what I did at work](https://github.com/oxidecomputer/omicron/blob/17510a64780b86733b39300cfea9946f9623f0dd/update-engine/examples/update-engine-basic/spec.rs#L137), and use this very simple impl:

```rust
fn path_schema(gen: &mut SchemaGenerator) -> Schema {
    let mut schema: SchemaObject = <String>::json_schema(gen).into();
    schema.format = Some("Utf8PathBuf".to_owned());
    schema.into()
}
```

and annotate your schema with `#[schemars(schema_with = "path_schema")]`.

This is too trivial to be copyrightable, but in case it ever is consider this to be CC0-1.0.
